/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface TestNone {
    }
    interface TestScoped {
    }
    interface TestShadow {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLTestNoneElement extends Components.TestNone, HTMLStencilElement {
    }
    var HTMLTestNoneElement: {
        prototype: HTMLTestNoneElement;
        new (): HTMLTestNoneElement;
    };
    interface HTMLTestScopedElement extends Components.TestScoped, HTMLStencilElement {
    }
    var HTMLTestScopedElement: {
        prototype: HTMLTestScopedElement;
        new (): HTMLTestScopedElement;
    };
    interface HTMLTestShadowElement extends Components.TestShadow, HTMLStencilElement {
    }
    var HTMLTestShadowElement: {
        prototype: HTMLTestShadowElement;
        new (): HTMLTestShadowElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "test-none": HTMLTestNoneElement;
        "test-scoped": HTMLTestScopedElement;
        "test-shadow": HTMLTestShadowElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface TestNone {
    }
    interface TestScoped {
    }
    interface TestShadow {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "test-none": TestNone;
        "test-scoped": TestScoped;
        "test-shadow": TestShadow;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "test-none": LocalJSX.TestNone & JSXBase.HTMLAttributes<HTMLTestNoneElement>;
            "test-scoped": LocalJSX.TestScoped & JSXBase.HTMLAttributes<HTMLTestScopedElement>;
            "test-shadow": LocalJSX.TestShadow & JSXBase.HTMLAttributes<HTMLTestShadowElement>;
        }
    }
}
